[package]
name = "charliechess"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
enum_str = "0.1.2"
num-derive = "0.4.2"
num-traits = "0.2.19"
ordered_hash_map = "0.4.0"
regex = "1.11.1"
strum = "0.27.1"
strum_macros = "0.27.1"
unwrap = "1.2.1"
